name: CI - Build & Health Check

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  docker-healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t iris-api .

      - name: Run container
        id: run_ct
        run: |
          # Por si quedó algo previo (no debería en runner limpio)
          docker rm -f irisapi 2>/dev/null || true
          docker run -d --name irisapi -p 5002:5002 iris-api
          docker ps

      - name: Wait for API (curl)
        id: wait_api
        run: |
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:5002/health > /dev/null; then
              echo "API is up"
              exit 0
            fi
            sleep 2
          done
          echo "API did not become healthy in time"
          exit 1

      - name: Predict smoke test
        run: |
          curl -fsS -X POST http://127.0.0.1:5002/predict \
            -H "Content-Type: application/json" \
            -d '{"features":[5.1,3.5,1.4,0.2]}' | tee result.json
          test -s result.json

      # Mostrar logs SOLO si el contenedor existe
      - name: Show container logs (always, if exists)
        if: always()
        run: |
          if docker ps -a --format '{{.Names}}' | grep -qx irisapi; then
            docker logs irisapi || true
          else
            echo "Container irisapi not found; skipping logs."
          fi

